---
- name: test playbook
  hosts: all
  become: true

  tasks: 
  - name: test a command
    shell: whoami
  - name: ensure apache is insatlled
    package: 
      name: apache2
      state: present

  - name: ensure apache is started
    service: 
      name: apache2
      state: started
      enabled: true

